
(setq blitz-keywords 
'( "new"  
 "for"  
 "if"  
 "else"  
 "end"  
 "true"  
 "false"  
 "null"  
 "case"  
 "then"  
 "elseif"  
 "select"  
 "default"  
 "and"  
 "or"  
 "until"  
 "wend"  
 "while" 
 "for"  
 "dim"  
 "each"  
 "to"  
 "function"  
 "const"  
 "include"  
 "next"  
 "goto"  
 "gosub"  
 "exit"  
 "step"  
 "type"  ))

(setq blitz-functions 
'( "else if" 
 "endif" 
 "end if" 
 "end select" 
 "not" 
 "repeat" 
 "forever" 
 "return" 
 "end function" 
 "type" 
 "field" 
 "end type" 
 "first" 
 "last" 
 "before" 
 "after" 
 "insert" 
 "delete" 
 "data" 
 "read" 
 "restore" 
 "pi" 
 "floor" 
 "ceil" 
 "sgn" 
 "abs" 
 "mod" 
 "sqr" 
 "sin" 
 "cos" 
 "tan" 
 "asin" 
 "acos" 
 "atan" 
 "atan2" 
 "exp" 
 "log" 
 "log10" 
 "xor" 
 "shl" 
 "shr" 
 "sar" 
 "rnd" 
 "rand" 
 "seedrnd" 
 "rndseed" 
 "left" 
 "right" 
 "mid" 
 "replace" 
 "instr" 
 "upper" 
 "lower" 
 "trim" 
 "lset" 
 "rset" 
 "chr" 
 "asc" 
 "len" 
 "hex" 
 "print" 
 "write" 
 "text" 
 "loadfont" 
 "setfont" 
 "freefont" 
 "fontwidth" 
 "fontheight" 
 "fontsize" 
 "fontname" 
 "fontstyle" 
 "stringwidth" 
 "stringheight" 
 "input" 
 "keydown" 
 "keyhit" 
 "getkey" 
 "waitkey" 
 "keywait" 
 "flushkeys" 
 "movemouse" 
 "mousedown" 
 "mousehit" 
 "getmouse" 
 "waitmouse" 
 "mousex" 
 "mousey" 
 "mousez" 
 "mousexspeed" 
 "mouseyspeed" 
 "mousezspeed" 
 "flushmouse" 
 "joytype" 
 "joydown" 
 "joyhit" 
 "joyx" 
 "joyy" 
 "joyz" 
 "joyu" 
 "joyv" 
 "joyxdir" 
 "joyydir" 
 "joyzdir" 
 "joyudir" 
 "joyvdir" 
 "joyyaw" 
 "joypitch" 
 "joyroll" 
 "joyhat" 
 "flushjoy" 
 "createbank" 
 "freebank" 
 "banksize" 
 "resizebank" 
 "copybank" 
 "peekbyte" 
 "peekshort" 
 "peekint" 
 "peekfloat" 
 "pokebyte" 
 "pokeshort" 
 "pokeint" 
 "pokefloat" 
 "openfile" 
 "readfile" 
 "writefile" 
 "closefile" 
 "filepos" 
 "seekfile" 
 "readdir" 
 "closedir" 
 "morefiles" 
 "nextfile" 
 "currentdir" 
 "changedir" 
 "createdir" 
 "deletedir" 
 "filetype" 
 "filesize" 
 "copyfile" 
 "deletefile" 
 "eof" 
 "readavail" 
 "readbyte" 
 "readshort" 
 "readint" 
 "readfloat" 
 "readstring" 
 "readline" 
 "readbytes" 
 "writebyte" 
 "writeshort" 
 "writeint" 
 "writefloat" 
 "writestring" 
 "writeline" 
 "writebytes" 
 "counthostips" 
 "hostip" 
 "dottedip" 
 "copystream" 
 "opentcpstream" 
 "closetcpstream" 
 "createtcpserver" 
 "accepttcpstream" 
 "closetcpserver" 
 "tcpstreamip" 
 "tcpstreamport" 
 "tcptimeouts" 
 "createudpstream" 
 "closeudpstream" 
 "sendudpmsg" 
 "recvudpmsg" 
 "udpstreamip" 
 "udpstreamport" 
 "udpmsgip" 
 "udpmsgport" 
 "udptimeouts" 
 "startnetgame" 
 "hostnetgame" 
 "joinnetgame" 
 "stopnetgame" 
 "createnetplayer" 
 "deletenetplayer" 
 "netplayername" 
 "netplayerlocal" 
 "recvnetmsg" 
 "netmsgtype" 
 "netmsgfrom" 
 "netmsgto" 
 "netmsgdata" 
 "sendnetmsg" 
 "openmovie" 
 "closemovie" 
 "drawmovie" 
 "moviewidth" 
 "movieheight" 
 "movieplaying" 
 "loadsound" 
 "freesound" 
 "loopsound" 
 "soundpitch" 
 "soundvolume" 
 "soundpan" 
 "playsound" 
 "playmusic" 
 "playcdtrack" 
 "stopchannel" 
 "pausechannel" 
 "resumechannel" 
 "channelpitch" 
 "channelvolume" 
 "channelpan" 
 "channelplaying" 
 "graphics" 
 "endgraphics" 
 "setbuffer" 
 "viewport" 
 "origin" 
 "flip" 
 "vwait" 
 "scanline" 
 "graphicsheight" 
 "graphicswidth" 
 "graphicsdepth" 
 "graphicsformat" 
 "graphicsbuffer" 
 "color" 
 "clscolor" 
 "cls" 
 "plot" 
 "line" 
 "rect" 
 "oval" 
 "getcolor" 
 "colorred" 
 "colorgreen" 
 "colorblue" 
 "countgfxmodes" 
 "countgfxdrivers" 
 "gfxdrivername" 
 "setgfxdriver" 
 "gfxmodewidth" 
 "gfxmodeheight" 
 "gfxmodedepth" 
 "gfxmodeformat" 
 "gfxmodeexists" 
 "totalvidmem" 
 "availvidmem" 
 "setgamma" 
 "updategamma" 
 "gammared" 
 "gammagreen" 
 "gammablue" 
 "lockbuffer" 
 "unlockbuffer" 
 "lockedpixels" 
 "lockedpitch" 
 "lockedformat" 
 "readpixel" 
 "writepixel" 
 "readpixelfast" 
 "writepixelfast" 
 "copypixel" 
 "copypixelfast" 
 "copyrect" 
 "frontbuffer" 
 "backbuffer" 
 "desktopbuffer" 
 "loadbuffer" 
 "savebuffer" 
 "loadimage" 
 "copyimage" 
 "createimage" 
 "loadanimimage" 
 "freeimage" 
 "saveimage" 
 "grabimage" 
 "imagebuffer" 
 "drawimage" 
 "drawimagerect" 
 "drawblockrect" 
 "drawblock" 
 "tileimage" 
 "tileblock" 
 "maskimage" 
 "handleimage" 
 "midhandle" 
 "automidhandle" 
 "scaleimage" 
 "resizeimage" 
 "rotateimage" 
 "tformimage" 
 "tformfilter" 
 "imagewidth" 
 "imageheight" 
 "imagexhandle" 
 "imageyhandle" 
 "imagesoverlap" 
 "imagescollide" 
 "rectsoverlap" 
 "imagerectoverlap" 
 "imagerectcollide" 
 "millisecs" 
 "delay" 
 "currentdate" 
 "currenttime" 
 "createtimer" 
 "freetimer" 
 "timerticks" 
 "resettimer" 
 "pausetimer" 
 "resumetimer" 
 "waittimer" 
 "hidepointer" 
 "showpointer" 
 "apptitle" 
 "commandline" 
 "systemproperty" 
 "queryobject" 
 "setenv" 
 "getenv" 
 "calldll" 
 "execfile" 
 "createprocess" 
 "autosuspend" 
 "runtimeerror" 
 "stop" 
 "debuglog" ))

(setq blitz-constants '("pi"))

(setq blitz-types
 '( "str" 
 "int" 
 "string" 
 "bin" 
 "float" 
 "local" 
 "global" ))

(setq blitz-keywords-regexp (regexp-opt blitz-keywords 'words))
(setq blitz-types-regexp (regexp-opt blitz-types 'words))
(setq blitz-constants-regexp (regexp-opt blitz-constants 'words))
(setq blitz-functions-regexp (regexp-opt blitz-functions 'words))

(setq blitz-keywords nil)
(setq blitz-types nil)
(setq blitz-constantsasd nil)
(setq blitz-functions nil)

(setq blitz-font-lock-keywords
 `(
   (,blitz-types-regexp . font-lock-type-face)
   (,blitz-constants-regexp . font-lock-constant-face)
   (,blitz-functions-regexp . font-lock-function-name-face)
   (,blitz-keywords-regexp . font-lock-keyword-face) 
))

(define-derived-mode blitz-plus-mode fundamental-mode
  "BlitzPlus  mode"
  "Major mode for blitzPlus"

  (setq font-lock-defaults '((blitz-font-lock-keywords)))

  (setq blitz-keywords-regexp nil)
  (setq blitz-types-regexp nil)
  (setq blitz-constants-regexp nil)
  (setq blitz-functions-regexp nil)
)

(provide 'blitz-plus-mode)
